plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: '@yarnpkg/plugin-typescript'

yarnPath: .yarn/releases/yarn-sources.cjs

packageExtensions:
  '@fullhuman/postcss-purgecss@*':
    peerDependencies:
      'postcss': '*'
