plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: '@yarnpkg/plugin-typescript'

yarnPath: .yarn/releases/yarn-3.0.0.cjs

packageExtensions:
  'styled-components@*':
    peerDependencies:
      babel-plugin-macros: '*'
