version: '3.1'

services:
  db:
    image: postgres:latest
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: dzone
      POSTGRES_PASSWORD: password

  caddy:
    image: caddy:latest
    restart: unless-stopped
    ports:
      - '5000:5000'
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./site:/srv
      - caddy_data:/data
      - caddy_config:/config

volumes:
  caddy_data:
    external: true
  caddy_config:
