# Name displayed on github
name: Builds

# Trigger the workflow on push or pull request
on:
  push:
    branches:
      - rewrite
  pull_request:
    branches:
      - rewrite

# Jobs run in parallel by default
jobs:
  builds:
    name: Build
    runs-on: ubuntu-latest
    steps: 
      # Steps are sequence of tasks
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - run: yarn install --check-cache
      # Run build scripts
      - run: yarn lerna run build
      # Gather coverage reports
      - run: yarn run collect-coverage
      # Post coverages to coverall
      - uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
